version: '2'
services:
  backend_db:
    image: mysql:5.7
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=backend
      - MYSQL_ROOT_PASSWORD=root
  backend:
    image: drytools/maven
    working_dir: /home/docker/backend
    volumes:
      - ../backend/:/home/docker/backend
    ports:
      - "8080:8080"
    links:
      - backend_db
    command: mvn spring-boot:run
  webapp:
    image: drytools/gulp-build
    working_dir: /home/docker/webapp
    volumes:
      - ../webapp/:/home/docker/webapp
      - /home/docker/webapp/node_modules
    ports:
      - "3000:3000"
    links:
      - backend
    command: /bin/bash -c "npm install --silent && bower install --allow-root && npm run dev-docker" 
     